
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace ClassificationModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ClassificationModel.ModelInput sampleData = new ClassificationModel.ModelInput()
            {
                Text = @"Please dont waste your money.",
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"Text: {@"Please dont waste your money."}");
            Console.WriteLine($"Label: {0F}");


            var sortedScoresWithLabel = ClassificationModel.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
